Gorevcim.WEB/Controllers/ImagesController.cs
using Microsoft.AspNetCore.Mvc;
using Gorevcim.Core.Services;
using Gorevcim.Core.DTOs;
using Gorevcim.Core;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using Gorevcim.Core.Models;
using Gorevcim.Repository.AppDbContexts.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Gorevcim.Service.Services;
using System.Web;
using System;
using System.IO;
using System.Drawing;
using Microsoft.AspNetCore.Mvc.RazorPages;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using static System.Net.Mime.MediaTypeNames;
using System.Text;

namespace Gorevcim.WEB.Controllers
{
    public class ImagesController : Controller
    {

        private readonly IImagesService _imagesService;
        private readonly IMapper _mapper;
        private readonly IHostingEnvironment _environment;

        public ImagesController (IImagesService imagesService, IMapper mapper,IHostingEnvironment environment)
        {
            _imagesService = imagesService;
            _mapper = mapper;
            _environment = environment;
        }
        public async Task<IActionResult> Index()
        {
            var images = await _imagesService.GetWebAllImages();
            dynamic mymodel = new ExpandoObject();
            mymodel._images = images;
            mymodel.activeImagesCount = images.Where(t => t.IsActive == 1).Count();
            mymodel.passiveImagesCount = images.Where(t => t.IsActive == 0).Count();
            return View(mymodel);
        }

        public async Task<IActionResult> Save()
        {
            var images = await _imagesService.GetAllAsync();
            var imagesDto = _mapper.Map<List<ImagesDto>>(images.ToList());
            ViewBag.images = new SelectList(imagesDto, "Id", "Name");
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Save(ImagesDto imagesDto,IFormFile file, string base64String)
        {
            var folderPath = Path.Combine(_environment.WebRootPath, "ImagesUploads");
            var filePath= Path.Combine(folderPath,file.FileName);

            DateTime date = DateTime.Now;
            string date_str = date.ToString("dd-MM-yyyy-HH-mm-ss-");
            var _imagesName = date_str + file.FileName;
            if (file.Length >0)
            {
                using (var stream = new FileStream(filePath,FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                byte[] bytes_array = System.IO.File.ReadAllBytes(filePath);
                base64String = Convert.ToBase64String(bytes_array);

                var _imagesPath = filePath;
                var _imagesBase64 = base64String;

                imagesDto.LogoBase64 = _imagesBase64;
                //imagesDto.ImageName = _imagesName;
                imagesDto.FilePath = _imagesPath;

                await _imagesService.AddAsync(_mapper.Map<Images>(imagesDto));
                TempData.Add("Success", "Resim başarıyla eklenmiştir.");
                return RedirectToAction(nameof(Index));

            }

            else
            {
                TempData.Add("Error", "Hata Oluştu. ImagesController|Save|83");
                return View();
            }

        }
    



     




    }





}

Gorevcim.WEB/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Gorevcim.Core.Services;
using Gorevcim.Core.DTOs;
using Gorevcim.Core.Models;
using Gorevcim.Core;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Gorevcim.Service.Services;

namespace Gorevcim.WEB.Controllers
{



    public class ProductsController : Controller
    {


        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IProductColorsService _productColorsService;
        private readonly IProductBrandsService _productBrandsService;      
        private readonly IProductProjectsService _productProjectsService;
        private readonly IProductCurrencyUnitsService _productCurrencyUnitsService;
        private readonly IProductMeasurementUnitsService _productMeasurementUnitsService;
        private readonly IProductVatUnitsService _productVatUnitsService;
        private readonly IProductWeightUnitsService _productWeightUnitsService;

        private readonly IProductFeaturesService _productFeaturesService;
        private readonly IMapper _mapper;

        public ProductsController(IProductService productService, ICategoryService categoryService, IProductColorsService productColorsService, IProductFeaturesService productFeaturesService, IProductBrandsService productBrandsService, IProductProjectsService productProjectsService, IProductCurrencyUnitsService productCurrencyUnitsService, IProductMeasurementUnitsService productMeasurementUnitsService, IProductVatUnitsService productVatUnitsService, IProductWeightUnitsService productWeightUnitsService, IMapper mapper)
        {
            _productService = productService;
            _categoryService = categoryService;
            _productColorsService = productColorsService;
            _productBrandsService = productBrandsService;
            _productProjectsService = productProjectsService;            
            _productCurrencyUnitsService = productCurrencyUnitsService;
            _productMeasurementUnitsService = productMeasurementUnitsService;
            _productVatUnitsService = productVatUnitsService;
            _productWeightUnitsService = productWeightUnitsService;

            _productFeaturesService = productFeaturesService;
            _mapper = mapper;   
        }

        public  async Task<IActionResult> Index()
        {
            var products = await _productService.GetWebAllProductsAsync();
            var categorys = await _categoryService.GetWebAllCategoriesAsync();
            var productsColors = await _productColorsService.GetWebAllProductColors();
            var productsBrands = await _productBrandsService.GetWebAllProductBrands();
            var productProjects= await _productProjectsService.GetWebAllProductProjects();
            var productCurrency = await _productCurrencyUnitsService.GetWebAllProductCurrency();
            var productMeasurement= await _productMeasurementUnitsService.GetWebAllProductMeasurement();
            var productVat = await _productVatUnitsService.GetWebAllProductVatUnits();
            var productWeight = await _productWeightUnitsService.GetWebAllProductWeightUnits();
            var productsFeatures = await _productFeaturesService.GetWebAllProductFeatures();



            dynamic mymodel = new ExpandoObject();
            mymodel._products = products;
            mymodel._categorys = categorys;
            mymodel._productsColors = productsColors; 
            mymodel._productsBrands = productsBrands;
            mymodel._productProjects = productProjects;
            mymodel._productCurrency = productCurrency;
            mymodel._productMeasurement = productMeasurement;
            mymodel._productVat = productVat;
            mymodel._productWeight = productWeight;
            mymodel._productsFeatures = productsFeatures;

            mymodel.activeProductsCount = products.Where(t => t.IsActive == 1).Count();
            mymodel.passiveProductsCount = products.Where(t => t.IsActive == 0).Count();

            return View(mymodel);

        }


        public async Task<IActionResult> Save()
        {
            var productscolor = await _productColorsService.GetWebAllColorsAsync();
            var productscolorDto = _mapper.Map<List<ProductColorsDto>>(productscolor.ToList());
            ViewBag.productsColor = new SelectList(productscolorDto, "Id", "Name");


            var productBrands = await _productBrandsService.GetAllAsync(); 
            var ProductBrandsDto = _mapper.Map<List<ProductBrandsDto>>(productBrands.ToList());
            ViewBag.productBrands = new SelectList(ProductBrandsDto, "Id", "BrandsName");


            var productProjects = await _productProjectsService.GetAllAsync();
            var ProductsProjectsDto = _mapper.Map<List<ProductProjectsDto>>(productProjects.ToList());
            ViewBag.productProject = new SelectList(ProductsProjectsDto, "Id", "Name");

            var productCurrency = await _productCurrencyUnitsService.GetAllAsync();
            var productCurrencyDto = _mapper.Map<List<ProductCurrencyUnitsDto>>(productCurrency.ToList());
            ViewBag.productCurrency = new SelectList(productCurrencyDto, "Id", "Name");

            var productMeasurement = await _productMeasurementUnitsService.GetAllAsync();
            var productMeasurementDto = _mapper.Map<List<ProductMeasurementUnitsDto>>(productMeasurement.ToList());
            ViewBag.productMeasurement = new SelectList(productMeasurementDto, "Id", "Name");

            var productVat = await _productVatUnitsService.GetAllAsync();
            var productVatDto = _mapper.Map<List<ProductVatUnitsDto>>(productVat.ToList());
            ViewBag.productVat = new SelectList(productVatDto, "Id", "Name");

            var productWeight = await _productWeightUnitsService.GetAllAsync();
            var productWeightDto = _mapper.Map<List<ProductWeightUnitsDto>>(productWeight.ToList());
            ViewBag.productWeight = new SelectList(productWeightDto, "Id", "Name");


            var categoryies =  await _categoryService.GetAllAsync();
            var categoryiesDto = _mapper.Map<List<CategoryDto>>(categoryies.ToList());           
            ViewBag.categories = new SelectList(categoryiesDto,"Id", "Name");
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Save(ProductDto productsDto, ProductFeaturesDto productFeaturesDto)
        {
            if (ModelState.IsValid)
            { 
                var _productId = await _productService.AddAsync(_mapper.Map<Products>(productsDto));
                productFeaturesDto.ProductId = _productId.Id;
                await _productFeaturesService.AddAsync(_mapper.Map<ProductFeatures>(productFeaturesDto));
                TempData.Add("Success", "Ürün Özellikleriyle birlikte eklenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Error", "Hata Oluştu.ProductController|Save|59");
            var categories = await _categoryService.GetAllAsync();
            var categoriesDto = _mapper.Map<List<CategoryDto>>(categories.ToList());   
            ViewBag.categories = new SelectList(categoriesDto,"Id", "Name");
            return View();
        }



         public async Task<IActionResult> Update(int Id)
         {
            var products = await _productService.GetByIdAsync(Id);
            var categories = await _categoryService.GetAllAsync();
            var categoriesDto = _mapper.Map<List<CategoryDto>>(categories.ToList());
            ViewBag.categories = new SelectList(categoriesDto,"Id", "Name", products.CategoryId);
            return View(_mapper.Map<ProductDto>(products));
         }


        public async Task<IActionResult> Details(int Id)
        {
            var products = await _productService.GetByIdAsync(Id);
            var categories = await _categoryService.GetAllAsync();
            var categoriesDto = _mapper.Map<List<CategoryDto>>(categories.ToList());
            ViewBag.categories = new SelectList(categoriesDto, "Id", "Name", products.CategoryId);
            return View(_mapper.Map<ProductDto>(products));
        }


        [HttpPost]
        public async Task<IActionResult> Update(ProductDto productsDto)
        {
            if (ModelState.IsValid)
            {
                await _productService.UpdateAsync(_mapper.Map<Products>(productsDto));
                TempData.Add("Info", "Ürün Güncellenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("info", "Hata Oluştu.ProductController|Update|89");
            var categories = await _categoryService.GetAllAsync();
            var categoriesDto = _mapper.Map<List<CategoryDto>>(categories.ToList());
            ViewBag.categories = new SelectList(categoriesDto, "Id", "Name", productsDto.CategoryId);
            return View(productsDto);
        }





        public async Task<IActionResult> Delete(int Id)
        {
            var products = await _productService.GetByIdAsync(Id);
            await _productService.RemoveAsync(products);
            TempData.Add("info", "Ürün başarılı şekilde silinmiştir.");
            return RedirectToAction(nameof(Index));
        }



    }
}

Gorevcim.WEB/Views/Images/Details.cshtml
@{
    ViewData["Title"] = "Update";
}
@model ImagesDto

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="Products" asp-action="Update" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Ürün Güncelle</h4>
                <input type="hidden" asp-for="Id" id="ProductsIdUpdate">

                <div class="mb-3 row">
                    <label asp-for="ImagesId" class="col-md-2 col-form-label" ></label>
                    <div class="col-md-6">
                        <select id="ImageIdUpdate" asp-for="ImagesId" asp-items="ViewBag.images" class="form-select" disabled readonly></select>
                        <span asp-validation-for="ImagesId" class="text-danger"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label asp-for="LogoBase64" class="col-md-2 col-form-label" for="ProductsNameSave">Adı</label>
                    <div class="col-md-6">
                        <input id="ProductsNameUpdate" asp-for="LogoBase64" type="text" class="form-control" disabled readonly required>
                        <div class="invalid-feedback">Ürün Adı Boş olamaz!</div>
                    </div>
                </div>

             

              
            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/Images/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model dynamic


<div class="row">
<div class="col-md-6 col-xl-2">
    <div class="card">
        <div class="card-body">
            <div>
                <p class="text-muted mb-0">Aktif Ürün Sayısı</p>
                <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.activeImagesCount</span></h5>                
            </div> 
        </div>
    </div>
</div>

<div class="col-md-6 col-xl-2">
    <div class="card">
        <div class="card-body">
            <div>
                <p class="text-muted mb-0">Pasif Ürün Sayısı</p>
                <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.passiveImagesCount</span></h5>                
            </div> 
        </div>
    </div>
</div>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Images Table</h4>
            <div class="table-rep-plugin">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="ImagesTable" role="grid">

                        <thead>
                            <tr>
                                <th>Id</th>                             
                                <th>Resim</th>
                         

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model._images)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.LogoBase64</td>
                                   
                                    <td>
                                        <ul class="list-inline mb-0">

                                            <li class="list-inline-item">
                                                <a class="px-2 text-info" asp-controller="Images" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="uil uil-arrow-from-right font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-primary" asp-controller="Images" asp-action="Update" asp-route-id="@item.Id">
                                                    <i class="uil uil-pen font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-danger" data-bs-toggle="modal" data-bs-target="#modalDelete@(item.Id)">
                                                    <i class="uil uil-trash-alt font-size-18"></i>
                                                </a>
                                            </li>
                                 
                                        </ul>
                                    </td>
                                </tr>
                                <div class="modal fade" id="modalDelete@(item.Id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="myModalLabel">Resim@(item.Name) siliniyor.</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    
                                                   <strong> Resim Id:</strong> @(item.Id)<br>
                                                    <strong>Resim:  @(item.Name)</strong>  <i>@(item.SalePrice)</i> kalıcı olarak   <strong>silinecektir.</strong>
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light waves-effect" data-bs-dismiss="modal">iptal</button>
                                                <a type="button" class="btn btn-primary waves-effect waves-light" asp-controller="Images" method="post" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>

                                <!-- /.modal -->
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>




</div>



@section Scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $('#ProductsCategoryTable').DataTable(

                {
                    language: {
                        info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                        infoEmpty: "Gösterilecek hiç kayıt yok.",
                        loadingRecords: "Kayıtlar yükleniyor.",
                        zeroRecords: "Tablo boş",

                        search: "Arama:",
                        infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                        buttons: {
                            copyTitle: "Panoya kopyalandı.",
                            copySuccess: "Panoya %d satır kopyalandı",
                            copy: "Kopyala",
                            print: "Yazdır",
                        },

                        paginate: {
                            first: "İlk",
                            previous: "Önceki",
                            next: "Sonraki",
                            last: "Son"
                        },
                    },
                    dom: 'Bfrltip',
                    buttons: [
                        'copy', 'excel', 'pdf', 'print'
                    ],
                    responsive: true

                }

            );
        });
    </script>

}

Gorevcim.WEB/Views/Images/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model ImagesDto




<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form  asp-action="Save" method="post" asp-controller="Images" class="needs-validation" novalidate>
                <h4 class="card-title">Resim Kayıt</h4>




            </form>


        </div>
    </div>

            <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <h4 class="card-title">Dropzone</h4>
                                <p class="card-title-desc">
                                    DropzoneJS is an open source library
                                    that provides drag’n’drop file uploads with image previews.
                                </p>

                                <div>
                                    <form action="#" class="dropzone">
                                        <div class="fallback">


                                            <input name="file" type="file" multiple="multiple">
                                        </div>
                                        <div class="dz-message needsclick">
                                            <div class="mb-3">
                                                <i class="display-4 text-muted uil uil-cloud-upload"></i>
                                            </div>

                                            <h4>Drop files here or click to upload.</h4>
                                        </div>
                           
                                    </form>

                     
                                </div>

                              
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->

         
                

  






</div>



<script type="text/javascript">
    function ProductsJsKaydet() {
        var data = $("#ProductsSaveHtmlForm").serialize();
        console.log(data);
        alert(data);
        $.ajax({
            type: 'POST',
            url: '/Products/Save',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8'
            data: data,
            success: function (result) {
                alert('Kayıt oluştu ');
                console.log(result);
            },
            error: function () {
                alert('kayıt Başarısız');
                console.log('Failed ');
            }
        })
    }

</script>

Gorevcim.WEB/Views/Images/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model ImagesDto

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="Images" asp-action="Update" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Ürün Güncelle</h4>
                 <input type="hidden" asp-for="Id"  id="ProductsIdUpdate">
               

                </form>       

                            <div class="row">
                                <div class="col-12">
                                    <div class="card">
                                        <div class="card-body">

                                            <h4 class="card-title">Dropzone</h4>
                                            <p class="card-title-desc">
                                                DropzoneJS is an open source library
                                                that provides drag’n’drop file uploads with image previews.
                                            </p>

                                            <div>
                                                <form action="#" class="dropzone">
                                                    <div class="fallback">


                                                        <input name="file" type="file" multiple="multiple">
                                                    </div>
                                                    <div class="dz-message needsclick">
                                                        <div class="mb-3">
                                                            <i class="display-4 text-muted uil uil-cloud-upload"></i>
                                                        </div>

                                                        <h4>Drop files here or click to upload.</h4>
                                                    </div>
                                                </form>
                                            </div>

                                            <div class="text-center mt-4">
                                                <button type="submit" class="btn btn-primary waves-effect waves-light">Güncelle</button>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                        </div> <!-- container-fluid -->
                    </div>






            
            

</div>